./install.sh#!/usr/bin/env bash
# =============================================================================
# Veralux Receptionist - Installer
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# API endpoint (TODO: update to your actual endpoint)
API_URL="https://api.veralux.ai/api/v1/installer/config"

# -----------------------------------------------------------------------------
# Gum Installation
# -----------------------------------------------------------------------------
GUM_VERSION="0.13.0"
GUM_BIN="$SCRIPT_DIR/.bin/gum"

install_gum() {
    local os arch url
    
    os="$(uname -s | tr '[:upper:]' '[:lower:]')"
    arch="$(uname -m)"
    
    case "$arch" in
        x86_64) arch="amd64" ;;
        aarch64|arm64) arch="arm64" ;;
        *) echo "Unsupported architecture: $arch"; exit 1 ;;
    esac
    
    case "$os" in
        darwin) os="Darwin" ;;
        linux) os="Linux" ;;
        *) echo "Unsupported OS: $os"; exit 1 ;;
    esac
    
    url="https://github.com/charmbracelet/gum/releases/download/v${GUM_VERSION}/gum_${GUM_VERSION}_${os}_${arch}.tar.gz"
    
    echo -e "${DIM}Downloading installer components...${NC}"
    mkdir -p "$SCRIPT_DIR/.bin"
    
    if command -v curl &> /dev/null; then
        curl -sL "$url" | tar -xzf - -C "$SCRIPT_DIR/.bin" gum
    elif command -v wget &> /dev/null; then
        wget -qO- "$url" | tar -xzf - -C "$SCRIPT_DIR/.bin" gum
    else
        echo -e "${RED}Error: curl or wget required${NC}"
        exit 1
    fi
    
    chmod +x "$GUM_BIN"
}

ensure_gum() {
    if [[ -x "$GUM_BIN" ]]; then
        return 0
    fi
    
    if command -v gum &> /dev/null; then
        GUM_BIN="gum"
        return 0
    fi
    
    install_gum
}

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
generate_secret() {
    # Generate URL-safe secret (no +, /, = characters)
    openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | xxd -p
}

check_docker() {
    if ! command -v docker &> /dev/null; then
        echo -e "${RED}✗ Docker is not installed${NC}"
        echo ""
        echo "  Please install Docker first:"
        echo "  https://docs.docker.com/get-docker/"
        exit 1
    fi
    
    if ! docker info &> /dev/null; then
        echo -e "${RED}✗ Docker is not running${NC}"
        echo ""
        echo "  Please start Docker and try again."
        exit 1
    fi
}

# -----------------------------------------------------------------------------
# API Functions
# -----------------------------------------------------------------------------
fetch_config() {
    local email="$1"
    local password="$2"
    local response
    
    response=$(curl -s -X POST "$API_URL" \
        -H "Content-Type: application/json" \
        -d "{\"email\": \"$email\", \"password\": \"$password\"}" \
        2>/dev/null) || {
        echo '{"success": false, "error": "Could not connect to server"}'
        return
    }
    
    echo "$response"
}

# -----------------------------------------------------------------------------
# Config Generation
# -----------------------------------------------------------------------------
write_env_file() {
    local api_key="${1:-}"
    local telnyx_number="${2:-}"
    local telnyx_api_key="${3:-}"
    local telnyx_public_key="${4:-}"
    local openai_api_key="${5:-}"
    local jwt_secret="${6:-}"
    local cloudflare_token="${7:-}"
    
    cat > .env << ENVFILE
# =============================================================================
# Veralux Receptionist - Configuration
# Generated by installer on $(date)
# =============================================================================

# Version & Registry
VERSION=latest
REGISTRY=ghcr.io/nick-veraluxai

# Database
POSTGRES_USER=veralux
POSTGRES_PASSWORD=$(generate_secret)
POSTGRES_DB=veralux

# Security
JWT_SECRET=${jwt_secret}
API_KEY=${api_key}

# Telnyx
TELNYX_API_KEY=${telnyx_api_key}
TELNYX_PUBLIC_KEY=${telnyx_public_key}
TELNYX_PHONE_NUMBER=${telnyx_number}

# OpenAI
OPENAI_API_KEY=${openai_api_key}

# Ports
CONTROL_PORT=4000
RUNTIME_PORT=4001

# Media
MEDIA_STREAM_TOKEN=$(generate_secret)
AUDIO_STORAGE_DIR=/app/audio

# Logging
LOG_LEVEL=info

# Speech-to-Text
STT_CHUNK_MS=100
STT_SILENCE_MS=700
DEAD_AIR_MS=10000

# Rate Limiting
GLOBAL_CONCURRENCY_CAP=100
TENANT_CONCURRENCY_CAP_DEFAULT=10
TENANT_CALLS_PER_MIN_CAP_DEFAULT=60
CAPACITY_TTL_SECONDS=3600

# GPU Services
WHISPER_PORT=9000
WHISPER_MODEL_SIZE=base
KOKORO_PORT=7001
KOKORO_VOICE_ID=default
XTTS_PORT=7002
XTTS_LANGUAGE=en

# Control Plane
SECRET_ENCRYPTION_KEY=$(generate_secret)
SECRET_MANAGER=db
ADMIN_ALLOWED_ORIGINS=http://localhost:4000,http://127.0.0.1:4000

# Runtime URLs
PUBLIC_BASE_URL=http://localhost:4001
AUDIO_PUBLIC_BASE_URL=http://localhost:4001
TTS_MODE=kokoro_http
KOKORO_URL=http://kokoro:7001

# Cloudflare Tunnel (optional)
CLOUDFLARE_TUNNEL_TOKEN=${cloudflare_token}
ENVFILE
}

# -----------------------------------------------------------------------------
# Main Installer
# -----------------------------------------------------------------------------
main() {
    clear
    
    # Banner
    echo ""
    echo -e "${BLUE}${BOLD}"
    echo "  ╔═══════════════════════════════════════════════════════════╗"
    echo "  ║                                                           ║"
    echo "  ║            VERALUX RECEPTIONIST                           ║"
    echo "  ║                     Setup                                 ║"
    echo "  ║                                                           ║"
    echo "  ╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
    
    # Check Docker
    echo -e "${DIM}Checking requirements...${NC}"
    check_docker
    echo -e "${GREEN}✓${NC} Docker is running"
    echo ""
    
    # Ensure gum is available
    ensure_gum
    
    # Check for existing config
    if [[ -f ".env" ]]; then
        echo -e "${YELLOW}Existing configuration found.${NC}"
        echo ""
        
        CHOICE=$("$GUM_BIN" choose --header "What would you like to do?" \
            "Start services (keep existing config)" \
            "Reconfigure (enter new credentials)" \
            "Exit")
        
        case "$CHOICE" in
            "Start services"*)
                echo ""
                ./deploy.sh up
                exit 0
                ;;
            "Exit")
                exit 0
                ;;
        esac
        echo ""
    fi
    
    # Load offline images if present
    if [[ -f "images.tar.zst" ]]; then
        echo -e "${BLUE}Offline bundle detected.${NC}"
        echo ""
        "$GUM_BIN" spin --spinner dot --title "Loading Docker images..." -- ./load-images.sh
        echo -e "${GREEN}✓${NC} Images loaded"
        echo ""
    fi
    
    # Main menu loop
    while true; do
        echo ""
        SETUP_METHOD=$("$GUM_BIN" choose --header "How would you like to set up?" \
            "Online Setup (log in with your account)" \
            "Offline Setup (enter setup code from email)" \
            "Admin Setup (Veralux staff only)" \
            "Exit")
        
        [[ "$SETUP_METHOD" == "Exit" ]] && exit 0
        
        echo ""
    
    if [[ "$SETUP_METHOD" == "Online"* ]]; then
        # =====================================================================
        # ONLINE SETUP
        # =====================================================================
        echo -e "${BOLD}Log in with your Veralux account${NC}"
        echo -e "${DIM}Enter the email and password from your signup.${NC}"
        echo -e "${DIM}(Leave blank and press Enter to go back)${NC}"
        echo ""
        
        EMAIL=$("$GUM_BIN" input --placeholder "Email address" --width 50)
        [[ -z "$EMAIL" ]] && continue
        
        PASSWORD=$("$GUM_BIN" input --placeholder "Password" --password --width 50)
        [[ -z "$PASSWORD" ]] && continue
        
        echo ""
        RESPONSE=$("$GUM_BIN" spin --spinner dot --title "Logging in..." -- \
            bash -c "curl -s -X POST '$API_URL' -H 'Content-Type: application/json' -d '{\"email\": \"$EMAIL\", \"password\": \"$PASSWORD\"}'")
        
        # Parse response
        SUCCESS=$(echo "$RESPONSE" | grep -o '"success":\s*true' || echo "")
        
        if [[ -z "$SUCCESS" ]]; then
            ERROR=$(echo "$RESPONSE" | grep -o '"error":\s*"[^"]*"' | cut -d'"' -f4 || echo "Login failed")
            echo -e "${RED}✗ $ERROR${NC}"
            echo ""
            echo "Please check your credentials and try again."
            echo "Don't have an account? Sign up at https://veralux.ai/signup"
            exit 1
        fi
        
        # Extract config from response
        API_KEY=$(echo "$RESPONSE" | grep -o '"api_key":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
        TELNYX_NUMBER=$(echo "$RESPONSE" | grep -o '"telnyx_number":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
        TELNYX_API_KEY=$(echo "$RESPONSE" | grep -o '"telnyx_api_key":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
        TELNYX_PUBLIC_KEY=$(echo "$RESPONSE" | grep -o '"telnyx_public_key":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
        OPENAI_API_KEY=$(echo "$RESPONSE" | grep -o '"openai_api_key":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
        JWT_SECRET=$(echo "$RESPONSE" | grep -o '"jwt_secret":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
        CLOUDFLARE_TOKEN=$(echo "$RESPONSE" | grep -o '"cloudflare_token":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
        
        echo -e "${GREEN}✓${NC} Logged in successfully"
        
    elif [[ "$SETUP_METHOD" == "Offline"* ]]; then
        # =====================================================================
        # OFFLINE SETUP
        # =====================================================================
        echo -e "${BOLD}Offline Setup${NC}"
        echo ""
        
        ENTRY_METHOD=$("$GUM_BIN" choose --header "How do you want to enter your credentials?" \
            "Paste setup code from email" \
            "Enter details manually" \
            "← Back")
        
        [[ "$ENTRY_METHOD" == "← Back" ]] && continue
        
        echo ""
        
        if [[ "$ENTRY_METHOD" == "Paste"* ]]; then
            echo -e "${DIM}Paste the setup code from your welcome email:${NC}"
            echo ""
            
            SETUP_CODE=$("$GUM_BIN" write --placeholder "Paste your setup code here..." --width 60 --height 5)
            
            # Decode base64
            DECODED=$(echo "$SETUP_CODE" | base64 -d 2>/dev/null) || {
                echo -e "${RED}✗ Invalid setup code${NC}"
                exit 1
            }
            
            # Extract values from JSON
            API_KEY=$(echo "$DECODED" | grep -o '"api_key":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
            TELNYX_NUMBER=$(echo "$DECODED" | grep -o '"telnyx_number":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
            TELNYX_API_KEY=$(echo "$DECODED" | grep -o '"telnyx_api_key":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
            TELNYX_PUBLIC_KEY=$(echo "$DECODED" | grep -o '"telnyx_public_key":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
            OPENAI_API_KEY=$(echo "$DECODED" | grep -o '"openai_api_key":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
            JWT_SECRET=$(echo "$DECODED" | grep -o '"jwt_secret":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
            CLOUDFLARE_TOKEN=$(echo "$DECODED" | grep -o '"cloudflare_token":\s*"[^"]*"' | cut -d'"' -f4 || echo "")
            
            echo -e "${GREEN}✓${NC} Setup code accepted"
            
        else
            echo -e "${DIM}Enter the details from your welcome email:${NC}"
            echo ""
            
            API_KEY=$("$GUM_BIN" input --placeholder "API Key (vx_...)" --width 50)
            TELNYX_NUMBER=$("$GUM_BIN" input --placeholder "Phone Number (+1...)" --width 50)
            TELNYX_API_KEY=$("$GUM_BIN" input --placeholder "Telnyx API Key" --password --width 50)
            TELNYX_PUBLIC_KEY=$("$GUM_BIN" input --placeholder "Telnyx Public Key" --width 50)
            OPENAI_API_KEY=$("$GUM_BIN" input --placeholder "OpenAI API Key (sk-...)" --password --width 50)
            JWT_SECRET=$("$GUM_BIN" input --placeholder "Your Password" --password --width 50)
            CLOUDFLARE_TOKEN=""  # Customers don't need to enter this manually
        fi
        
    elif [[ "$SETUP_METHOD" == "Admin"* ]]; then
        # Admin setup - no API_KEY needed
        API_KEY=""
        # =====================================================================
        # ADMIN SETUP
        # =====================================================================
        echo -e "${BOLD}${YELLOW}Admin Setup${NC}"
        echo -e "${DIM}This mode is for Veralux staff only.${NC}"
        echo ""
        
        # Admin authentication
        echo -e "${DIM}(Leave blank and press Enter to go back)${NC}"
        echo ""
        
        ADMIN_USER=$("$GUM_BIN" input --placeholder "Admin username" --width 50)
        [[ -z "$ADMIN_USER" ]] && continue
        
        ADMIN_PASS=$("$GUM_BIN" input --placeholder "Admin password" --password --width 50)
        [[ -z "$ADMIN_PASS" ]] && continue
        
        # Verify admin credentials
        if [[ "$ADMIN_USER" != "VeraLux" || "$ADMIN_PASS" != "fuzzyone" ]]; then
            echo ""
            echo -e "${RED}✗ Invalid admin credentials${NC}"
            echo ""
            "$GUM_BIN" confirm "Try again?" && continue || exit 1
        fi
        
        echo ""
        echo -e "${GREEN}✓${NC} Admin authenticated"
        echo ""
        
        # Quick setup - just the keys
        echo -e "${BOLD}Enter configuration:${NC}"
        echo ""
        
        OPENAI_API_KEY=$("$GUM_BIN" input --placeholder "OpenAI API Key (sk-...)" --password --width 50)
        TELNYX_API_KEY=$("$GUM_BIN" input --placeholder "Telnyx API Key" --password --width 50)
        TELNYX_PUBLIC_KEY=$("$GUM_BIN" input --placeholder "Telnyx Public Key" --width 50)
        TELNYX_NUMBER=$("$GUM_BIN" input --placeholder "Telnyx Phone Number (+1...)" --width 50)
        JWT_SECRET=$("$GUM_BIN" input --placeholder "Password / JWT Secret" --password --width 50)
        
        echo ""
        echo -e "${DIM}Optional: Cloudflare Tunnel (leave blank to skip)${NC}"
        CLOUDFLARE_TOKEN=$("$GUM_BIN" input --placeholder "Cloudflare Tunnel Token (eyJ...)" --password --width 50)
        
        echo ""
        echo -e "${DIM}Telnyx #: $TELNYX_NUMBER${NC}"
        echo ""
        
        "$GUM_BIN" confirm "Deploy with this configuration?" || continue
    fi
    
    # Break out of menu loop - configuration collected successfully
    break
    done
    
    # Write configuration
    echo ""
    "$GUM_BIN" spin --spinner dot --title "Saving configuration..." -- \
        bash -c "$(declare -f write_env_file generate_secret); write_env_file '$API_KEY' '$TELNYX_NUMBER' '$TELNYX_API_KEY' '$TELNYX_PUBLIC_KEY' '$OPENAI_API_KEY' '$JWT_SECRET' '$CLOUDFLARE_TOKEN'"
    
    echo -e "${GREEN}✓${NC} Configuration saved"
    
    # Start services
    echo ""
    echo -e "${BOLD}Starting services...${NC}"
    echo ""
    
    # Start with Cloudflare tunnel if token is provided
    if [[ -n "$CLOUDFLARE_TOKEN" ]]; then
        echo -e "${DIM}Starting with Cloudflare Tunnel...${NC}"
        ./deploy.sh tunnel cloudflare
    else
        ./deploy.sh up
    fi
    
    # Success
    echo ""
    echo -e "${GREEN}${BOLD}"
    echo "  ╔═══════════════════════════════════════════════════════════╗"
    echo "  ║                                                           ║"
    echo "  ║                   SETUP COMPLETE! ✓                       ║"
    echo "  ║                                                           ║"
    echo "  ╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
    echo "  Your Veralux Receptionist is now running!"
    echo ""
    echo -e "  ${DIM}Commands:${NC}"
    echo "    ./deploy.sh status   - Check service status"
    echo "    ./deploy.sh logs     - View logs"
    echo "    ./deploy.sh restart  - Restart services"
    echo "    ./deploy.sh down     - Stop services"
    echo ""
}

main "$@"
